django/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import  views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/insta/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.list, name='list'),
    path('explore/', views.explore, name='explore'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),   # post_id 라는 변수명은 views.py 에서 받아오는 변수명과 같아야한다
    path('<int:post_id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:post_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'), # 어떤 게시글에, 누가 쓴 댓글 삭제할 것인지
    path('<int:post_id>/like/', views.like, name='like'),
    ]

django/insta/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


def post_image_path(instance, filename):
    return f'posts/image/{filename}'
    
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
                                    # 외래키: 이 테이블 外 에서 가져온 어떤 키를 여기에 담아둔다
                                    # 원래는 ForeignKey(User) : 장고는 기본적으로 User 라는 테이블을 알아서 만들어 둠
                                    # 근데 장고가 만든 User 테이블말고, 자기가 customize 한 테이블 쓰고 싶으면
                                    # settings 를 import 해서 바꿔주면 됨 : User → settings.AUTH_USER_MODEL
                                    # on_delete = models.CASCADE 란? 1:N 관계에서 1의 정보가 삭제되면 N 도 삭제된다 (탈퇴하면 글 다 삭제)
                                    # 그 외 여러가지 옵션이 있음 (공식문서 model field reference)
                                    # PROTECT : n이 있으면 1을 삭제 못함  ( 글 남아있으면 탈퇴 못함)
                                    # SET_NULL : 주인이 없는 상태로 그냥 둠  (CASCADE 보다 더 빈도) : 탈퇴했으나 카페에 글은 有
                                    # SET_DEFAULT : 기본값으로 바꿈
                                    # SET() : 내가 설정한 걸로 바꿈
                                    # DO_NOTHING : 그냥 아무것도 안 함
    content = models.TextField()
    # image = ProcessedImageField(
    #     upload_to = post_image_path,
    #     processors=[ResizeToFill(600,600)], # 처리할 작업 목록
    #     format = 'JPEG', # 저장 포맷
    #     options = {'quality':90}, # 옵션
    #     )
    
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')  # 좋아요 누른 user 들
    
    
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)   # post 와 이미지를 1:n 관계
    file = ProcessedImageField(
                upload_to = post_image_path,
                processors=[ResizeToFill(600,600)], # 처리할 작업 목록
                format = 'JPEG', # 저장 포맷
                options = {'quality':90}, # 옵션
        )
    
    
    
        
class Comment(models.Model): # 2중 1:N    [글 : 댓글입력자 = 글 : 댓글 = 1:N]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)   # foreignkey 의 첫번째 인자 = 어떤 테이블과 관계를 맺을 것인지
                                                                                   # on_delete 옵션 必
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    
    

django/insta/posts/forms.py
from django import forms
from .models import Post, Comment, Image

class PostForm(forms.ModelForm):  # 사용하려면, views.py에서 import 해줘야함 
    class Meta:
        model = Post    # 어떠한 모델의 폼을 작성할 거니? Post 라는 모델의 폼을 만들거야
        fields = ['content',]   # models.py 에 작성된 Post 클래스의 content 필드와 이미지필드


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]
        
ImageFormSet = forms.inlineformset_factory(Post,Image,form=ImageForm,extra=3)
# 첫번째 인자 : 부모 모델 (1:n 관계에서 1 역할, 이미지를 데리고 있을 애 = 글 )
# 두번째 인자 : 생성할 모델 ( 이미지 모델)
# 무슨 폼을 사용하는지
# 몇 개의 이미지폼을 엮을 것인지 = 이미지 폼 3개를 쓸 수 있음

        
class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'댓글을 작성하세요'}))  
                                         # 클래스 2개 넣고 싶으면 띄어쓰고 쓰면 됨 ex) 'class': 'form-control blue red'
                                         # form-control : form 을 예쁘게 꾸며 주는 
                                         # attrs = attributes 약자
                                         # models.py 에서 textfield 로 만들었는데, 댓글창이 너무 커서 못생겼으니까 작게 바꿔주는 작업
                                         # 한 줄 짜리 input 태그로 바뀜
                                         # content 라는 라벨도 안 보임 (label='') 때문에
                                         # charfield 는 저장할 수 있는 최대 길이가 제한되어 있음 그러므로 보여주는 건 charfield 로 보여주고
                                         # 실제로 저장해주는 형식인 models.py  는 textfield 로 남겨둠
    class Meta:
        model = Comment
        fields = ['content']
        
    

django/insta/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_http_methods
from .forms import PostForm, CommentForm, ImageFormSet
from .models import Post, Comment
from django.db import transaction
from itertools import chain
from django.http import JsonResponse
# Create your views here.


def explore(request):
    posts = Post.objects.order_by('-id').all()
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {'posts':posts, 'comment_form':comment_form})


@login_required
def list(request):
    #posts = Post.objects.order_by('-id').all()
    
    # 1. 내가 follow 하고 있는 사람들의 리스트 >> 나를 추가
    followings = request.user.followings.all()
    # 1-1. followings 변수와 나를 묶
    followings = chain(followings, [request.user])
    # 2. 이 사람들이 작성한 글들만 뽑아옴
    posts = Post.objects.filter(user__in=followings).order_by('-id')  # user 아이디가 followings 에 있는 사람들 글만 posts 에 넣음
    comment_form = CommentForm()
    return render(request, 'posts/list.html', {'posts':posts, 'comment_form':comment_form})
    

@login_required   # decorator 도 하나의 함수,  decorator 의 parameter 로 아래 create 함수를 넘겨줌, 그러므로 함수 앞에 써야한다
                  # 아래 함수를 실행하기 위해서는, 로그인이 되어 있어야 한다 의미
                  # 로그인 안 된 상태에서, 글쓰기 페이지로 들어가면, 자동으로 login 페이지로 돌림
                  # 넘어간 login 페이지 주소창 끝에는 'next=posts/create' 가 표시되어 있음 ( 이 주소로 시도했다가 튕겼다고 표시)
                  # 로그인 후 next 로 보내려면 코드 추가해 주면 됨 (accounts/views.py 에)
def create(request):
    if request.method =='POST':
        #post_form = PostForm(request.POST, request.FILES)
        
        post_form = PostForm(request.POST)  # post_form 에는 더이상 이미지파일이 올라가지 않으므로 files 삭제
        image_formset = ImageFormSet(request.POST, request.FILES) # 이미지폼은 post 도 있어야 함(왜인지는 잘...-_-)
        
        if post_form.is_valid() and image_formset.is_valid():  # 저장해도 되는 값이 들어왔으면
            post = post_form.save(commit=False)  # 객체를 만들었으나, 아직 DB에 저장은 x (commit=False 덕분에)
            post.user = request.user  # post 라는 객체의 user 칸에  request 의 user 를 가져와서 받아줌
            
            # post 와 이미지가 1:n 관계라서, post 가 먼저 존재해야, 이미지가 만들어짐
            with transaction.atomic():   # import 해야함
            # 1️⃣ 일단 post 를 만들어야한다
                post.save()  # 저장 = 실제 DB 에 반영
                
                # 2️⃣그후에 image를 저장할 수 있다
                image_formset.instance = post  # image_formset 은 이미지를 만들기 위한 애긴 한데, 3개를 한꺼번에 wrap 해뒀음(extra=3)
                                               # 꺼내기 위해서, instance 붙여줌?
                                               # 근데 post.save() 라는 코드를 실행하고, 확실히 저장을 확인한 뒤에, 다음 문장을 실행하는 게 아니라서
                                               # 오류가 생길 수 있다. 즉 실제 db에서는 이미지가 먼저 저장되고, post 가 저장될 수 있다는 의미
                                               # 이걸 막기위하여, 장고에서 제공하는 method 가  = with transaction.atomic()
                                               
                image_formset.save() # 부모에 대한 정보를 넣고, save 한다 라고 일단 이해를 하라고 하심
                        
                                    
            return redirect('posts:list') 
            
        
    else:  # get방식이면
        post_form = PostForm()
        image_formset = ImageFormSet
        
    return render(request, 'posts/form.html', {'post_form' : post_form, 'image_formset':image_formset,})  # 템플릿에서 쓰기 위하여 딕셔너리 key형태로 변수 넘겨줌
    
@login_required        
def delete(request, post_id):
    # post = Post.objects.get(pk=post_id)   # 존재하지 않는 key 로 삭제버튼 누르려고 하면, 에러
    post = get_object_or_404(Post, id=post_id)   # 존재하지 않는 key 로 삭제버튼을 누르려고 하면, page not found 페이지 보여줌
    
    if post.user != request.user:
        return redirect('posts:list')
        
    post.delete()
    return redirect('posts:list')
    
    
@login_required        
def update(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if post.user != request.user:
        return redirect('posts:list')
    
    if request.method == 'POST':  # 그냥 submit 버튼 눌렀을 때
        post_form = PostForm(request.POST, instance=post)
        image_formset = ImageFormSet(request.POST, request.FILES, instance=post)
        if post_form.is_valid() and image_formset.is_valid():
            post_form.save()
            image_formset.save()  # update 하는 시점에서는 post 가 만들어진 게 확실하니까 transaction 필요 x
            return redirect('posts:list')
        
    else:  # get요청 = 주소창에 주소 입력했을 때
        post_form = PostForm(instance=post)
        image_formset = ImageFormSet(instance=post)
    return render(request, 'posts/form.html', {'post_form':post_form, 'image_formset':image_formset,})

@login_required    
@require_POST    
def comment_create(request, post_id):  # 특정 글에 댓글을 달아야 하니까, post_id 변수 必
    comment_form = CommentForm(request.POST)   # 댓글을 작성하는 건 get 요청이 필요없음. 그러므로 따로 if문 필요 x
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.post_id = post_id
        comment.save()
    #return redirect('posts:list') # 댓글을 작성하는 페이지가 따로 있는 건 아니고, 해당 글 밑에 그냥 쓰는 거니까 따로 페이지 만들지 x
    return JsonResponse({
        'id' : comment.id,
        'postId' : post_id,
        'username' : comment.user.username,
        'content' : comment.content
    })

    




# a 태그는 post 요청을 보낼 수 없다. post 요청은 form 태그만 사용할 수 있음
# post 요청 데코레이터 쓰면, 그냥 삭제버튼만 만들어도 될 걸, form 태그로 바꿔줘야하는 번거로움 있음
# 그러므로, 그냥 get 요청 들어가도 (a 태그의 href 목적지) 삭제 되도록 설정
@require_http_methods(['GET','POST'])
def comment_delete(request, post_id, comment_id): # 주소쓸 때, post_id 가 먼저 들어가므로 변수 순서 지킬 것
    comment = get_object_or_404(Comment, id=comment_id)
    if comment.user != request.user: # 댓글의 주인이 아니면
        return redirect('posts:list')  # 목록으로 돌려보내라
        
    comment.delete()
    return redirect('posts:list')
    
@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    if request.user in post.like_users.all():  # post 를 좋아한 사람들 안에 현재 로그인한 사람이 있으면
        post.like_users.remove(request.user)  # 좋아요 취소
        liked = False
    
    else:
        post.like_users.add(request.user) # 현재 로그인한 유저가 해당 포스터를 좋아요 누르는 행위
                                          # post.like_users  (포스터를 좋아한 유저들 목록에)  add(request.user) 로그인한 user 를 더해
        liked = True
    
    #return redirect('posts:list')
    return JsonResponse({'liked':liked, 'count': post.like_users.count()})
    

django/insta/posts/templates/posts/_post.html
<div class="card" style="width: 18rem;">
  <div class="card-header">
    {% if post.user.profile.image %}
    <img src="{{ post.user.profile.image.url }}" width="25" alt="">
    {% endif %}
    <span>{{ post.user.username }}</span>
  </div>
  
  <!-- carousel 부분 -->
  <div id="post_{{ post.id }}" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <!-- 이미지 반복 돌려서 출력 -->
      {% for image in post.image_set.all %}
      <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}"> <!-- 첫번째 사진에만 active 가 걸리는 조건문 -->
        <img src="{{ image.file.url }}" class="card-img-top" alt="{{ image.file }}">
      </div>
      {% endfor %}
    </div>
    <a class="carousel-control-prev" href="#post_{{ post.id }}" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#post_{{ post.id }}" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  
  
  
  
  
  
  <div class="card-body">
    <!--<a href="{% url 'posts:like' post.id %}">-->
    
    <i class="{% if user in post.like_users.all %}fas{% else %}far{% endif %} fa-heart like-button" data-id="{{ post.id }}"></i>
    
      <!--{% if user in post.like_users.all %} <!-- 좋아요 눌렀으면 꽉 찬 하트 -->
      <!--  <i class="fas fa-heart"></i>-->
      <!--{% else %}  <!-- 아니면 -->
      <!--  <i class="far fa-heart"></i>  <!-- 빈 하트 -->
      <!--{% endif %}-->
    <!--</a>-->
    
    <p class="card-text">
      <span id="like-count-{{ post.id }}">{{ post.like_users.count }}</span> 명이 좋아합니다
    </p>
  </div>
  
  
  
  <div class="card-body">
    <p class="card-text">{{ post.content }}</p>
    
    {% if post.user == user %}   <!-- == 띄어써야 함 -->
    <a href="{% url 'posts:update' post.id %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'posts:delete' post.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
    
  </div>
  
  <div class="card-body" id="comment-list-{{ post.id }}">
    {% for comment in post.comment_set.all %}
    <div class="card-text">
      <strong>{{ comment.user.username }}</strong>{{ comment.content }}
      {% if comment.user == user %}  <!-- 댓글 주인과, 현재 로그인한 user 가 같으면 -->
      <a href="{% url 'posts:comment_delete' post.id comment.id %}">삭제</a>  <!-- 띄어쓰기 지켜야 -->
      {% endif %}
    </div>
    {% empty %}   <!-- html 에서만 쓸 수 있는 문법. 만약에 post.comment_Set.all 이 비어있으면(=반복을 돌릴 것이 없으면) 아래 구문行-->-->
    <!--  <div class="card-text">댓글이 없습니다.</div>-->
    {% endfor %}
  </div>
  
  {% if user.is_authenticated %}  <!-- 로그인 했을 때만 댓글작성 창을 보여줘 -->
  <form action={% url 'posts:comment_create' post.id %} method="POST" class="comment-form">
    {% csrf_token %}
    
    <!--# bootstrap 에서 input group 검색하면 button addons 있음 (input 오른쪽에 제출버튼 있는 거)-->
    <div class="input-group">
    {{ comment_form }}
    <div class="input-group-append">
      <input type="submit" value="Submit" class="btn btn-primary"/>
    </div>
    </div>

  </form>
  {% endif %}
  
</div>

django/insta/posts/templates/posts/create.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1>New Post</h1>

<form action =""  method ="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock %}

django/insta/posts/templates/posts/form.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1>Post Form</h1>

<form action =""  method ="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form post_form %}  <!-- post_form 에 bootstra_form 을 입혀서 보여줘 -->
    
    {{ image_formset.as_p }}  <!-- 각각의 image form set 을 p 태그로 감쌈. 줄바꿈 위하여 . 없으면 가로로 쭉 -->
    
    {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
    {% endbuttons %}
</form>

{% endblock %}

django/insta/posts/templates/posts/list.html
{% extends 'base.html' %}

{% block container %}

<h1>Post List</h1>

{% for post in posts %}

{% include 'posts/_post.html' %}

{% endfor %}


<script>
    const likeButtons = document.querySelectorAll('.like-button')  //좋아요 버튼이 많으므로, 해당 클래스를 가진 모든 버튼을 가져와야함 querySelectorAll
    // 반복문
    likeButtons.forEach(function(button){  // fuction(button) 에 하나의 버튼이 들어감
        button.addEventListener('click', function(event){ // 하트버튼을 클릭했을 때, event의 target 에 data-id 정보가 들어있음(?)
            console.log(event);
            const postId = event.target.dataset.id
            axios.get(`/posts/${postId}/like/`)
                    .then(function(response){
                        //console.log(response)
                        document.querySelector(`#like-count-${postId}`).innerText = response.data.count
                        if (response.data.liked) {  // response.date = {liked:true, count : 1}  // 좋아요 눌렀으면
                            event.target.classList.remove('far')   // 흰색 하트를 제거하고
                            event.target.classList.add('fas')  // 채워진 하트를 더해
                        } else {
                            event.target.classList.remove('fas')
                            event.target.classList.add('far')
                        }
                    })
        })
    })
    
    
    const commentForms = document.querySelectorAll('.comment-form')  // 댓글쓰는 폼은 여러개니까, ALL 로
    commentForms.forEach(function(form) {
        form.addEventListener('submit', function(event){  // submit 이라는 이벤트. submit 이벤트는 폼태그만 쓸 수 있음 . 폼태그의 제출버튼을 누르는 순간 작동하라는 의미
            event.preventDefault()  // 폼태그가 기본적으로 글작성하고 새로고침하는데, 이 기본설정을 막아버리기 위한 작성
                                    // 문제는 이렇게 하면, 폼태그의 작성기능까지 막아버려서, 댓글이 안 써짐
            console.log(event)
            
            // 내용인식시키기
            // event.target === form 임
            const data = new FormData(event.target)    // html 클래스말고, 파이썬 클래스느낌
            /* FormData 라는 클래스를 사용
               event.target (=폼태그) 에 담긴 정보를 담는 FormData 라는 바구니 */
               
               // Inspect FormData ( FormData 안에 뭐 들어있는지 조사해보기)
                for (const item of data.entries()) {
                    console.log(item)  // 댓글 우왕 입력하면 토큰이랑 ["content", "우왕"] 콘솔에 출력
                }
                
                // 이제 포스트 요청 보내기 (이제 댓글 써짐)
                axios.post(event.target.action, data)  // event.target 이 하나의 폼태그이므로, 그의 action = post 요청 보낼 url 을 말함
                    .then(function(response){
                        //console.log(response)
                        const comment = response.data
                        const commentList = document.querySelector(`#comment-list-${comment.postId}`) //jsonresponse 에 넘겼던 postId
                        const newComment = 
                        `
                        <div class="card-text">
                              <strong>${ comment.username }</strong>${ comment.content }
                                <a href="/posts/${comment.postId}/comments/${comment.id}/delete/">삭제</a>
                        </div>
                        `
                        commentList.insertAdjacentHTML('beforeend', newComment)  // element 끝나기 전에 삽입, newComment 삽입
                        event.target.reset()
                    })
        })
    })
</script>

{% endblock %}