django/insta/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.password, name='password'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
    ]

django/insta/insta/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import  views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('posts/', include('posts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]   

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/insta/accounts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) 
    # user 삭제되면 프로필도 필요없으니 CASCADE 옵션
    # 아래, 닉네임과, 소개, 이미지는 회원가입시 필수사항이 아니므로 빈칸 허용
    
    nickname = models.CharField(max_length=40, blank=True) # 닉네임작성
    introduction = models.TextField(blank=True) # 자기소개 작성
    image = ProcessedImageField( # 프로필이미지
                blank=True,
                upload_to = 'profile/images',  #이미지 저장 위치
                processors=[ResizeToFill(300,300)], # 처리할 작업 목록
                format = 'JPEG', # 저장 포맷
                options = {'quality':90}, # 옵션
        )
        


class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings') 
    # 이렇게 하면 장고가 제공하는 USER 클래스가 들어가있음
    # 후에, 우리가 만든 User 로 바꿔주는 설정 해줘야됨
    # 그래야 오류가 안 남
    # user.followings 랑 user.followrs 둘 다 가능하다. (무슨말이지?)
                                                            

django/insta/posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings


def post_image_path(instance, filename):
    return f'posts/image/{filename}'
    
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  
                                    # 외래키: 이 테이블 外 에서 가져온 어떤 키를 여기에 담아둔다
                                    # 원래는 ForeignKey(User) : 장고는 기본적으로 User 라는 테이블을 알아서 만들어 둠
                                    # 근데 장고가 만든 User 테이블말고, 자기가 customize 한 테이블 쓰고 싶으면
                                    # settings 를 import 해서 바꿔주면 됨 : User → settings.AUTH_USER_MODEL
                                    # on_delete = models.CASCADE 란? 1:N 관계에서 1의 정보가 삭제되면 N 도 삭제된다 (탈퇴하면 글 다 삭제)
                                    # 그 외 여러가지 옵션이 있음 (공식문서 model field reference)
                                    # PROTECT : n이 있으면 1을 삭제 못함  ( 글 남아있으면 탈퇴 못함)
                                    # SET_NULL : 주인이 없는 상태로 그냥 둠  (CASCADE 보다 더 빈도) : 탈퇴했으나 카페에 글은 有
                                    # SET_DEFAULT : 기본값으로 바꿈
                                    # SET() : 내가 설정한 걸로 바꿈
                                    # DO_NOTHING : 그냥 아무것도 안 함
    content = models.TextField()
    # image = ProcessedImageField(
    #     upload_to = post_image_path,
    #     processors=[ResizeToFill(600,600)], # 처리할 작업 목록
    #     format = 'JPEG', # 저장 포맷
    #     options = {'quality':90}, # 옵션
    #     )
    
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_posts')  # 좋아요 누른 user 들
    
    
class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)   # post 와 이미지를 1:n 관계
    file = ProcessedImageField(
                upload_to = post_image_path,
                processors=[ResizeToFill(600,600)], # 처리할 작업 목록
                format = 'JPEG', # 저장 포맷
                options = {'quality':90}, # 옵션
        )
    
    
    
        
class Comment(models.Model): # 2중 1:N    [글 : 댓글입력자 = 글 : 댓글 = 1:N]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)   # foreignkey 의 첫번째 인자 = 어떤 테이블과 관계를 맺을 것인지
                                                                                   # on_delete 옵션 必
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    
    

django/insta/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Profile

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm): # UserChangeForm 을 상속받아서 custom 하겠다
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name','last_name',] #수정 하고 싶은 4가지
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction', 'image',]

django/insta/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, ProfileForm, CustomUserCreationForm
from .models import Profile

# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
        
    if request.method == 'POST':
        signup_form = CustomUserCreationForm(request.POST)
        if signup_form.is_valid():
            # 회원가입하면, 바로 로그인 시켜주도록 하기
            user = signup_form.save()
            Profile.objects.create(user=user)  # User의 Profile 생성
            auth_login(request,user)
            return redirect('posts:list')
        
    else: # get 방식 요청
        signup_form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'signup_form': signup_form})
    
    
def login(request):
    if request.user.is_authenticated:
        return redirect('posts:list')
        
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():   # 실제 존재하는 user 인지 확인
            auth_login(request, login_form.get_user())   # login_form 에 입력된 user 정보를 가져와서 반환해줌
            return redirect(request.GET.get('next') or 'posts:list')  # next 가 있으면 next 가 우선이니까 앞에 적어야 한다
            
    else:
        login_form = AuthenticationForm()
    return render(request, 'accounts/login.html',{'login_form':login_form})
    
    
# 로그아웃은 따로 보여주는 페이지가 없으니까, redirect 로 끝냄    
def logout(request):
    auth_logout(request)  # request 안에 들어있는 user 정보를 제거해서 로그아웃함
    return redirect('posts:list')
    

def people(request, username):
    # get_user_model()  #=> User,
    people = get_object_or_404(get_user_model(), username=username)  # 앞의 username=column, 뒤에 username = 주소로부터 넘겨받은
    return render(request, 'accounts/people.html', {'people':people})
    
    
# User Edit(회원정보 수정) - User CRUD 중 U
@login_required
def update(request):
    if request.method == 'POST':
        user_change_form = CustomUserChangeForm(request.POST, instance=request.user) # 어떤 user 를 수정할건지에 대한 정보 필요
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('people', request.user.username)
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
    return render(request,'accounts/update.html', {'user_change_form': user_change_form}) # 회원정보수정페이지로 연결
    
    
# User Delete(회원탈퇴) - User CRUD 중 D
@login_required
def delete(request):
    if request.method == "POST":
        request.user.delete()
        return redirect('posts:list')
    return render(request, 'accounts/delete.html')
    

@login_required
def password(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save() # 비밀번호 변경되는 순간 = user 인증 만료
            update_session_auth_hash(request, user) # 비밀번호 변경 후, 자동로그인풀림방지
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)  # 어떠한 유저의 비밀번호를 변경할 것인지 인자 필요
    return render(request, 'accounts/password.html', {'password_change_form':password_change_form})
    

def profile_update(request):
    profile = request.user.profile
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
            
    else:
        profile_form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_update.html', {'profile_form':profile_form})
    
    
def follow(request, user_id):
    people = get_object_or_404(get_user_model(), id=user_id)
    
    # 1. people 을 unfollow 하기
    # 이 사람을 follow 하는 사람들의 리스트 = people.followers
    if request.user in people.followers.all(): # 이미 팔로우 목록에 있으면
        people.followers.remove(request.user)   # action 은 팔로우취소
    
    # 2. people을 follow 하기
    else: # 팔로우 중이 아니면
        people.followers.add(request.user) # 리스트에 나를 추가 (add)
    return redirect('people', people.username)

django/insta/accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block container %}

<h1>User Delete</h1>

<form method="POST">
    {% csrf_token %}
    <p>정말 탈퇴하시겠습니까?😥</p>
    <input type="submit" value="탈퇴할래요"/>
</form>

{% endblock %}

django/insta/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block container %}

<h1>로그인</h1>

<form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

django/insta/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}
<h1>Password Change</h1>


<form method='POST'>
    {% csrf_token %}
    {% bootstrap_form password_change_form %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

django/insta/accounts/templates/accounts/people.html
{% extends 'base.html' %}

{% block container %}

<div class="container">
    
    <div class="row">
        <div class="col-3">
            {% if people.profile.image %}
            <img src="{{ people.profile.image.url }}" width="50" alt="{{ people.profile.image }}"></img>
            {% endif %}
            <h1>{{ people.username }}</h1>
        </div>
        <div class="col-9">
            <div>
                <strong>{{ people.profile.nickname }}</strong><br><br>
                
                {% if user != people %} <!-- 현재 사용자말고 타인의 페이지일 경우에만 follow 버튼 보여줘 -->
                    {% if user in people.follower.all %}
                    <a href="{% url 'accounts:follow' people.id %}">팔로우취소</a>
                    {% else %}
                    <a href="{% url 'accounts:follow' people.id %}">팔로우</a>
                    {% endif %}
                {% endif %}
            </div>
            
            <div>
                <strong>Followers:</strong> {{ people.followers.count }}  <!--people을 팔로우 하고 있는 사람 수 -->
                <strong>Followings:</strong> {{ people.followings.count }} <!-- 내가 팔로우 하고 있는 사람 수 -->
            </div> 
            
            <div>
               {{ people.profile.introduction }}
            </div>
        </div>
    </div>
    
    
    {% if user == people %}  <!-- 현재 로그인 사람과, user 가 같으면 , 회원정보수정페이지 보여줘 -->
    <div>
        <a href="{% url 'accounts:profile_update' %}">프로필 정보 수정</a><br>
        <a href="{% url 'accounts:update' %}">계정 정보 수정</a>
    </div>
    {% endif %}
    
    <div class="row">
        {% for post in people.post_set.all %}
        <div class="col-4">
            <img src="{{ post.image_set.first.file.url }}" class="img-fluid"/> <!--post 가 가지고 있는 첫번째 파일 url -->
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

django/insta/accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block container %}
<h1>Profile Edit</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form profile_form %}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

django/insta/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block container %}

<h1>회원 가입</h1>

<form method="POST">
    {% csrf_token %}
    {{ signup_form }}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

django/insta/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block container %}

<h1>User Edit</h1>

<form method="POST">
    {% csrf_token %}
    {% bootstrap_form user_change_form %}
    <input type="submit" name="submit"/>
</form>

<h3>User Delete</h3>
<a href="{% url 'accounts:delete' %}" class="btn btn-danger">탈퇴하기🤣</a>
{% endblock %}